import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthContext from './context/AuthContext'
import ToasterContext from './context/ToasterContext'
import EditModal from './components/modals/EditModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kelvin Social',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} suppressContentEditableWarning={true}>
      <body className={inter.className} suppressContentEditableWarning={true}>
        <AuthContext>
          <EditModal />
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
